# Generated by Django 4.2.5 on 2023-10-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
